### ISSUE TITLE
Sum propagation in clp(fd)

### ISSUE THREAD

**Issue by erlanger** [triska/clpz#11]
If I have
```
A #= B + C + D, A #< 300, B #> 0, C #>0, D #> 0
```
A stronger propagation should be added stating that 
```
B #< 300, C #< 300, D #< 300
```

**Comment by UWN** [comment]
But, this **is** the case, in fact even more so. You get `[B,C,D] ins 1..297`!

**Comment by erlanger** [comment]
You're right, I must have mistyped something.
