### ISSUE TITLE
Domain error after some level of backtracking with clpz: error(domain_error(clpz_expression,[]),unknown([])-1)

### ISSUE THREAD

**Issue by david-sitsky** [triska/clpz#16]
I am sure this is completely my fault, but it is not entirely clear to me what this error means.  Am I mixing clpz expressions in some non-compatible way?

I have a very "naive" implementation of the following predicate to detect what numeric position (0-based) an element is within a list which I have run using scryer prolog and clpz:

```
:- use_module(library(lists)).
:- use_module(library(clpz)).

member_at_position(L, [L|_], 0).
member_at_position(L, [_|Ls], N) :-
    N #> 0,
    length(Ls, Length),
    Limit #= Length + 1,
    N #< Limit,
    member_at_position(L, Ls, M),
    N #= M+1.
```
Here is some interaction with the console which shows this issue:

```
?- member_at_position(a, [a,b,c,a,d], P).
   P = 0
;  caught: error(domain_error(clpz_expression,[]),unknown([])-1)
?- member_at_position(a, L, P).
   L = [a|_A], P = 0
;  L = [_A,a], P = 1
;  L = [_A,a,_B], P = 1
;  L = [_A,_B,a], P = 2
;  L = [_A,a,_B,_C], P = 1
;  caught: error(domain_error(clpz_expression,[]),unknown([])-1)
?- member_at_position(E, L, P).
   L = [E|_A], P = 0
;  L = [_A,E], P = 1
;  L = [_A,E,_B], P = 1
;  L = [_A,_B,E], P = 2
;  L = [_A,E,_B,_C], P = 1
;  caught: error(domain_error(clpz_expression,[]),unknown([])-1)
```
I am sure I am at fault here, but could you explain what is wrong please?

**Comment by UWN** [comment]
You are not at fault for this particular error. Very good find! (It's hard to narrow it down any further, because then also some other issues arise...) That said, there are probably better ways to express what you intend.

**Comment by UWN** [comment]
At least that last error occurs also when using `freeze/2` in the remaining fragment of your program.

**Comment by david-sitsky** [comment]
As a point of comparison, I tried the same code but using module clpfd with SWI and it seemed to work fine.  I realise clpfd is not the same as clpz though.

Is this the right place to mention this issue, or should I report it on Scryer's Github?

**Comment by UWN** [comment]
(it seems you are reading this here by e-mail. If you are reading it via the [web-interface](https://github.com/triska/clpz/issues/16) you see any mentioning in other places directly.)

**Comment by UWN** [comment]
> I realise clpfd is not the same as clpz though.

clpfd in SWI is the predecessor to clpz with about 2 (CPU-)centuries of [testing](http://www.complang.tuwien.ac.at/ulrich/swi-prolog/item3addendumORIG). Unfortunately, SWI got [non-conforming](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/SWI7_and_ISO) and also had a lot of instability in the [unification interface](https://github.com/SWI-Prolog/issues/issues/109) which rendered all the testing less useful than it could have been.

It seems that the issue you found is not directly related to clpz and expect it to be fixed soon.

**Comment by david-sitsky** [comment]
@UWN - excellent - thanks for letting me know.

**Comment by UWN** [comment]
In case there is nothing left, would you mind closing the isse?
