### ISSUE TITLE
nvalue/2 non-monotonic

### ISSUE THREAD

**Issue by UWN** [triska/clpz#9]
(i3a#372)

<pre>
| ?- B=1, B in 1..2, C in 1..2, #(A)#> #(B),nvalue(A,[B,B,C]),labeling([],[B,C]).
B = 1,
C = 2,
A = 2 ? ;
no
| ?-      B in 1..2, C in 1..2, #(A)#> #(B),nvalue(A,[B,B,C]),labeling([],[B,C]).
<strong>no</strong>
</pre>

It's not the labeling:

<pre>
| ?- B=1, B in 1..2, C in 1..2, #(A)#> #(B),nvalue(A,[B,B,C]), A = 2, B = 1, C = 2.
B = 1,
C = 2,
A = 2 ? ;
no
| ?-      B in 1..2, C in 1..2, #(A)#> #(B),nvalue(A,[B,B,C]), A = 2, B = 1, C = 2.
<strong>no</strong>
</pre>

In fact, both can be generalized to:

<pre>
| ?-       B in 1..2, C in 1..2, #(A)#> #(B),nvalue(A,[B,B,C]).
<strong>no</strong>
</pre>

**Comment by triska** [comment]
It works correctly in the latest version, please have a look.
